apiVersion: v1
kind: Service
metadata:
  name: selenium-grid
spec:
  selector:
    app: selenium-grid
  ports:
    - port: 4444
      targetPort: 4444
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-grid
spec:
  selector:
    matchLabels:
      app: selenium-grid
  template:
    metadata:
      labels:
        app: selenium-grid
    spec:
      containers:
        - name: selenium-grid
          image: seleniarm/standalone-firefox:latest
          env:
            - name: START_XVFB
              value: "false"
            # Enables concurrent sessions (aka "friends") in Codeception.
            - name: SE_NODE_MAX_SESSIONS
              value: "4"
            - name: SE_NODE_OVERRIDE_MAX_SESSIONS
              value: "true"
            - name: SE_NODE_SESSION_TIMEOUT
              value: "60"
          resources:
            limits:
              memory: "2Gi"
              cpu: "700m"
            requests:
              memory: "1Gi"
              cpu: "400m"
          ports:
            - containerPort: 4444
            - containerPort: 5900
            - containerPort: 7900
