apiVersion: batch/v1
kind: CronJob
metadata:
  name: bhreserve
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: bhreservationcontainerized:latest
              name: bhreserve
              imagePullPolicy: IfNotPresent
              env:
                - name: SEARCHTERMS
                  valueFrom:
                    configMapKeyRef:
                      name: bhreserve
                      key: searchterms
                - name: BH_USER
                  valueFrom:
                    secretKeyRef:
                      name: bhreserve
                      key: BH_USER
                - name: BH_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: bhreserve
                      key: BH_PASSWORD
                - name: SMTP_HOST
                  valueFrom:
                    secretKeyRef:
                      name: bhreserve
                      key: SMTP_HOST
                - name: SMTP_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: bhreserve
                      key: SMTP_USERNAME
                - name: SMTP_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: bhreserve
                      key: SMTP_PASSWORD
                - name: SMTP_TO
                  valueFrom:
                    secretKeyRef:
                      name: bhreserve
                      key: SMTP_TO
                - name: SMTP_FROM
                  valueFrom:
                    secretKeyRef:
                      name: bhreserve
                      key: SMTP_FROM
              volumeMounts:
                - mountPath: "/data"
                  name: bhreserve-pv
          restartPolicy: OnFailure
          volumes:
            - name: bhreserve-pv
              persistentVolumeClaim:
                claimName: bhreserve-pv
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bhreserve
data:
  searchterms: '["test","SPIEGEL","Spektrum","National"]'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bhreserve-pv
spec:
  storageClassName: localstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

---
# How do we want it implemented
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bhreserve-pv
spec:
  storageClassName: localstorage
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt/d/pvc
    type: DirectoryOrCreate
