---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bhreserve-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "oci-fss-sc"
  resources:
    requests:
      storage: 10Mi
